[simulation]
models = ["freq"]
source = [2.5, 2.5, 1.0]
receiver = [7.5, 7.5, 1.0]
omega_start = 100.0
omega_end = 1000.0
omega_points = 1000
sound_speed = 1500.0
cutoff_time = 2.0

[room]
Lx = 10.0
Ly = 10.0
Lz = 2.0
beta_wall = 0.9
beta_surface = 0.8

[computation]
use_gpu = true
batch_size = 8192
output_file = "greens_function_results.pt"